# Memory retrieval profiles by intent
# Each intent has customized retrieval parameters

intents:
  quote_request:
    description: "User requesting shipping quotes or pricing"
    k_em: 5
    k_sm: 12
    entity_types:
      - shipper
      - port
      - incoterm
      - commodity
    prefer_recent: true
    rerank_enabled: true
    
  compliance_query:
    description: "Questions about regulations, documentation, customs"
    k_em: 3
    k_sm: 15
    entity_types:
      - country
      - regulation
      - hs_code
    prefer_verified: true
    rerank_enabled: true
    
  shipment_tracking:
    description: "Tracking shipment status and delivery"
    k_em: 8
    k_sm: 5
    entity_types:
      - shipper
      - shipment_id
      - port
    prefer_recent: true
    rerank_enabled: false
    
  general:
    description: "General queries and clarifications"
    k_em: 5
    k_sm: 8
    entity_types: []
    prefer_recent: false
    rerank_enabled: true

# Global defaults (used when intent not matched)
defaults:
  k_em: 5
  k_sm: 10
  rerank_enabled: true
  prefer_recent: false
  prefer_verified: false
